#!/usr/bin/env python3
"""
generate_format_utils.py

Fetches the latest vk.xml, checks versioning, and auto-generates HelFormatUtils.hpp.
Verifies format existence by performing a trial compilation, filtering out missing formats.
"""

import re
import os
import sys
import subprocess
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

VK_XML_URL = "https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/main/xml/vk.xml"

# Force relative resolution based on script path
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
OUTPUT_DIR = REPO_ROOT / "engine" / "rhi" / "generated"
OUTPUT_PATH = OUTPUT_DIR / "HelFormatUtils.hpp"
TEMP_CPP_PATH = OUTPUT_DIR / "test_compile.cpp"

HEADER_TEMPLATE = """/* *************************************************************************  */
/*                                                                            */
/*  File: HelFormatUtils.hpp                                                  */
/*  AUTO-GENERATED — do not edit by hand.                                     */
/*  Generated by generate_format_utils.py from the Vulkan registry (vk.xml).  */
/*                                                                            */
/* *************************************************************************  */

#pragma once

#include <vulkan/vulkan.h>
#include <cstdint>
#include <string_view>

#ifdef HEL_FORMAT_NOT_DEFINED
#undef HEL_FORMAT_NOT_DEFINED
#endif

// This header was generated against Vulkan-Headers VK_HEADER_VERSION {header_version}.

namespace hel {{

// Returns the byte size of one texel block for `format`, or 0 if `format`
// is not a format this table knows about.
constexpr uint32_t\tgetFormatTexelSize(VkFormat format) {{
\tswitch (format) {{
{texel_cases}
\t\tdefault: return 0;
\t}}
}}

// Returns the aspect mask for `format`: color, depth, stencil, or
// depth|stencil combined.
constexpr VkImageAspectFlags\tgetFormatAspect(VkFormat format) {{
\tswitch (format) {{
{aspect_cases}
\t\tdefault: return 0;
\t}}
}}



enum class NumericType : uint8_t {{
\tUnknown,
\tUnorm,
\tSnorm,
\tUscaled,
\tSscaled,
\tUint,
\tSint,
\tUfloat,
\tSfloat,
\tSrgb
}};

constexpr NumericType\tUnknown_N = NumericType::Unknown;
constexpr NumericType\tUnorm_N = NumericType::Unorm;
constexpr NumericType\tSnorm_N = NumericType::Snorm;
constexpr NumericType\tUscaled_N = NumericType::Uscaled;
constexpr NumericType\tSscaled_N = NumericType::Sscaled;
constexpr NumericType\tUint_N = NumericType::Uint;
constexpr NumericType\tSint_N = NumericType::Sint;
constexpr NumericType\tUfloat_N = NumericType::Ufloat;
constexpr NumericType\tSfloat_N = NumericType::Sfloat;
constexpr NumericType\tSrgb_N = NumericType::Srgb;

// Returns the numeric type for `format`: Unorm, Snorm, Sfloat, Srgb, etc.
constexpr NumericType\tgetFormatNumericType(VkFormat format) {{
\tswitch (format) {{
{numeric_cases}
\t\tdefault: return Unknown_N;
\t}}
}}

// Returns a string_view corresponding to format.
constexpr std::string_view\tgetFormatName(VkFormat format) {{
\tswitch (format) {{
{name_cases}
\t\tdefault: return "Unknown_format";
\t}}
}}

// Checks if two formats share identical data type signage / encoding.
// Essential for layout validation during operations like vkCmdBlitImage.
constexpr bool	isSameDataType(VkFormat formatA, VkFormat formatB) {{
	auto	typeA = getFormatNumericType(formatA);
	auto	typeB = getFormatNumericType(formatB);
	if (typeA == Unknown_N || typeB == Unknown_N) {{
		return false;
	}}
	return typeA == typeB;
}}

}}
"""


def fetch_vk_xml(url: str) -> bytes:
	with urllib.request.urlopen(url) as resp:
		return resp.read()


def get_header_version(root: ET.Element) -> int:
	for typ in root.findall("types/type"):
		if typ.get("name") == "VK_HEADER_VERSION" or (typ.find("name") is not None and typ.find("name").text == "VK_HEADER_VERSION"):
			text = "".join(typ.itertext())
			for tok in text.split():
				if tok.isdigit():
					return int(tok)
	raise RuntimeError("Could not find VK_HEADER_VERSION in vk.xml")


def parse_formats(xml_bytes: bytes):
	root = ET.fromstring(xml_bytes)
	formats_block = root.find("formats")
	if formats_block is None:
		raise RuntimeError("No <formats> block found in vk.xml")

	entries = []
	for fmt in formats_block.findall("format"):
		name = fmt.get("name")
		block_size = fmt.get("blockSize")
		if name is None or block_size is None:
			continue

		components = fmt.findall("component")
		comp_names = {c.get("name") for c in components}
		is_multiplanar = any(c.get("planeIndex") is not None for c in components)

		has_depth = "D" in comp_names
		has_stencil = "S" in comp_names

		if is_multiplanar:
			aspect = "VK_IMAGE_ASPECT_COLOR_BIT"
		elif has_depth and has_stencil:
			aspect = "VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT"
		elif has_depth:
			aspect = "VK_IMAGE_ASPECT_DEPTH_BIT"
		elif has_stencil:
			aspect = "VK_IMAGE_ASPECT_STENCIL_BIT"
		else:
			aspect = "VK_IMAGE_ASPECT_COLOR_BIT"

		num_fmt = "Unknown"
		if components:
			raw_num = components[0].get("numericFormat")
			if raw_num:
				num_fmt = raw_num.lower().capitalize()

		entries.append((name, int(block_size), aspect, num_fmt))

	return entries


def get_existing_version() -> int:
	if not OUTPUT_PATH.exists():
		return -1
	content = OUTPUT_PATH.read_text()
	match = re.search(r"VK_HEADER_VERSION\s+(\d+)", content)
	if match:
		return int(match.group(1))
	return -1


def render_header(entries, version, undefined_formats=None):
	if undefined_formats is None:
		undefined_formats = set()

	texel_lines = []
	aspect_lines = []
	seen = set()

	unique_entries = []
	for entry in entries:
		name = entry[0]
		if name not in seen:
			seen.add(name)
			unique_entries.append(entry)

	def generate_switch_cases(entries_list, block_type):
		lines = []
		in_guard_block = False

		for i, (name, block_size, aspect, num_fmt) in enumerate(entries_list):
			is_undefined = name in undefined_formats

			if is_undefined and not in_guard_block:
				lines.append("#ifdef HEL_FORMAT_NOT_DEFINED")
				in_guard_block = True

			if block_type == "texel":
				lines.append(f"\t\tcase {name}: return {block_size}u;")
			elif block_type == "aspect":
				lines.append(f"\t\tcase {name}: return {aspect};")
			elif block_type == "numeric":
				lines.append(f"\t\tcase {name}: return {num_fmt}_N;")
			elif block_type == "name":
				lines.append(f"\t\tcase {name}: return \"{name}\";")

			next_is_undefined = False
			if i + 1 < len(entries_list):
				next_is_undefined = entries_list[i + 1][0] in undefined_formats

			if in_guard_block and not next_is_undefined:
				lines.append("#endif")
				in_guard_block = False

		return "\n".join(lines)

	texel_cases = generate_switch_cases(unique_entries, "texel")
	aspect_cases = generate_switch_cases(unique_entries, "aspect")
	numeric_cases = generate_switch_cases(unique_entries, "numeric")
	name_cases = generate_switch_cases(unique_entries, "name")

	return HEADER_TEMPLATE.format(
		texel_cases=texel_cases,
		aspect_cases=aspect_cases,
		numeric_cases=numeric_cases,
		name_cases=name_cases,
		header_version=version,
	)

def test_compile() -> list:
	# Write tiny verification program
	TEMP_CPP_PATH.write_text(
		f'#include "{OUTPUT_PATH.name}"\n\nint main(void) {{\n\treturn 0;\n}}\n'
	)

	cxx = os.environ.get("CXX", "g++")
	cmd = [cxx, "-std=c++20", "-fsyntax-only", str(TEMP_CPP_PATH)]

	include_dir = REPO_ROOT / "engine"
	cmd += [f"-I{include_dir}"]

	result = subprocess.run(cmd, capture_output=True, text=True)

	if TEMP_CPP_PATH.exists():
		TEMP_CPP_PATH.unlink()

	if result.returncode == 0:
		return []

	errors = result.stderr + result.stdout
	failed_formats = re.findall(r"'(VK_FORMAT_[A-Za-z0-9_]+)'", errors)
	if not failed_formats:
		failed_formats = re.findall(r"\b(VK_FORMAT_[A-Za-z0-9_]+)\b.*not declared", errors)

	return list(set(failed_formats))


def main():
	print("Fetching latest vk.xml from Khronos...")
	try:
		xml_bytes = fetch_vk_xml(VK_XML_URL)
	except Exception as e:
		print(f"Error fetching vk.xml: {e}", file=sys.stderr)
		sys.exit(1)

	root = ET.fromstring(xml_bytes)
	latest_version = get_header_version(root)
	existing_version = get_existing_version()

	if latest_version == existing_version:
		print(f"HelFormatUtils.hpp is already up to date with version {latest_version}. No update needed.")
		return

	print(f"Updating header from version {existing_version} to {latest_version}...")
	entries = parse_formats(xml_bytes)

	OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

	# Step 1: Write an initial file assuming all formats exist
	header_content = render_header(entries, latest_version)
	OUTPUT_PATH.write_text(header_content)

	# Step 2: Compile check to spot formats missing from the local environment's SDK
	print("Running diagnostic compilation pass...")
	undefined_formats = test_compile()

	# Step 3: If elements failed, rebuild and overwrite the header with guards applied
	if undefined_formats:
		print(f"Found {len(undefined_formats)} missing formats in local Vulkan SDK. Wrapping in guards...")
		header_content = render_header(entries, latest_version, set(undefined_formats))
		OUTPUT_PATH.write_text(header_content)

	print(f"Generation successful: {OUTPUT_PATH}")


if __name__ == "__main__":
	main()