#!/usr/bin/env python3
"""
generate_system_json.py

Generates:
	1) one JSON file per ISystem-derived class found under usr/<target>/systems/
	2) a single generated_systems.cpp that includes every system header and
		registers each class with the engine.

Usage:
	python3 generate_system_json.py <target> \
		[--json-output-dir DIR] [--cpp-output FILE]
"""

import argparse
import json
import re
import sys
from pathlib import Path

SYSTEM_PATTERN = re.compile(
	r'class\s+(\w+)\s*:\s*(?:public|private|protected)?\s*ISystem\s*\{',
	re.MULTILINE,
)

HEADER_EXTENSIONS = ("*.hpp", "*.h")

CPP_TEMPLATE = """/* *************************************************************************  */
/*                                                                            */
/*  File: generated_systems.cpp                                               */
/*  AUTO-GENERATED — do not edit by hand.                                     */
/*  Generated by scripts/generate_system_json.py for target '{target}'.
/*                                                                            */
/* *************************************************************************  */

{includes}

namespace\thel {{

{registrations}

}}
"""


def find_systems(systems_dir: Path):
	"""Returns list of (class_name, header_path) tuples, headers only."""
	results = []
	for pattern in HEADER_EXTENSIONS:
		for path in systems_dir.rglob(pattern):
			text = path.read_text(encoding="utf-8", errors="ignore")
			for match in SYSTEM_PATTERN.finditer(text):
				results.append((match.group(1), path))
	return results


def write_json(systems, systems_dir: Path, output_dir: Path):
	output_dir.mkdir(parents=True, exist_ok=True)
	for stale in output_dir.rglob("*.json"):
		stale.unlink()

	seen = set()
	for name, path in systems:
		if name in seen:
			continue
		seen.add(name)

		rel_path = path.relative_to(systems_dir)
		data = {"name": name, "source": rel_path.as_posix()}

		out_subdir = output_dir / rel_path.parent
		out_subdir.mkdir(parents=True, exist_ok=True)

		out_file = out_subdir / f"{name}.json"
		with out_file.open("w", encoding="utf-8") as f:
			json.dump(data, f, indent=4)
		print(f"generated: {out_file}")

	return seen


def render_cpp(systems, systems_dir: Path, target: str):
	seen = set()
	include_lines = []
	registration_lines = []

	for name, path in systems:
		if name in seen:
			continue
		seen.add(name)

		rel_path = path.relative_to(systems_dir).as_posix()
		include_lines.append(f'#include "systems/{rel_path}"')
		registration_lines.append(f'SystemRegistrar<sys::{name}> reg_{name}System;')

	includes = "\n".join(include_lines)
	registrations = "\n".join(registration_lines)

	return CPP_TEMPLATE.format(
		target=target,
		includes=includes,
		registrations=registrations,
	)


def write_cpp(systems, systems_dir: Path, target: str, cpp_output: Path):
	cpp_output.parent.mkdir(parents=True, exist_ok=True)
	content = render_cpp(systems, systems_dir, target)
	cpp_output.write_text(content, encoding="utf-8")
	print(f"generated: {cpp_output}")


def main():
	parser = argparse.ArgumentParser(
		description="Generate per-system JSON descriptors and a registration cpp."
	)
	parser.add_argument("target", help="Target name under usr/ (e.g. editor)")
	parser.add_argument("--json-output-dir", default=None)
	parser.add_argument("--cpp-output", default=None)
	args = parser.parse_args()

	script_dir = Path(__file__).resolve().parent
	root_dir = script_dir.parent
	target_dir = root_dir / "usr" / args.target
	systems_dir = target_dir / "systems"

	if not systems_dir.is_dir():
		print(f"error: systems directory not found: {systems_dir}", file=sys.stderr)
		sys.exit(1)

	json_output_dir = (
		Path(args.json_output_dir) if args.json_output_dir else target_dir / "systems_json"
	)
	cpp_output = (
		Path(args.cpp_output) if args.cpp_output else root_dir / "build" / "generated" / "generated_systems.cpp"
	)

	systems = find_systems(systems_dir)
	if not systems:
		print(f"warning: no ISystem classes found in {systems_dir}", file=sys.stderr)

	seen = write_json(systems, systems_dir, json_output_dir)
	write_cpp(systems, systems_dir, args.target, cpp_output)

	print(f"Total systems generated: {len(seen)}")


if __name__ == "__main__":
	main()